<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>UD_Relic_Revealer</AssemblyName>
		<PackageId>UD_Relic_Revealer</PackageId>
		<Authors>UnderDoug</Authors>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <BaseIntermediateOutputPath>.dotnet\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>.dotnet\bin\</BaseOutputPath>
  </PropertyGroup>
  <Import Project="../Mods.csproj" />
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Mod\Textures\" />
  </ItemGroup>
</Project>
